packages:
  - 'examples/*'
  - 'packages/*'

catalog:
  'typescript': ^5.8.3
  '@types/node': ^22.15.33
  'sass': ^1.89.2
  'sass-embedded': ^1.89.2
  'vite': ^6.3.5
  'vitest': ^3.2.4
  'prettier': ^3.6.1
  '@vitest/browser': ^3.2.4
  '@playwright/test': ^1.53.1

catalogs:
  react:
    'react': ^19.1.0
    'react-dom': ^19.1.0
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
  formatter:
    '@ianvs/prettier-plugin-sort-imports': ^4.4.2
    prettier-plugin-packagejson: ^2.5.15
    prettier: ^3.6.1
  linter:
    '@eslint/js': ^9.29.0
    '@eslint/eslintrc': ^3.3.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.5
    eslint: ^9.29.0
    typescript-eslint: ^8.35.0
    jiti: '^2.4.2'
  scripts:
    taze: ^19.1.0
