packages:
  - "examples/*"
  - "packages/*"

catalog:
  "typescript": ^5.7.3
  "@types/node": ^22.0.0
  "sass": ^1.83.4
  "vite": ^6.0.5

catalogs:
  react:
    "react": ^19.0.0
    "react-dom": ^19.0.0
    "@types/react": ^19.0.8
    "@types/react-dom": ^19.0.3
