packages:
  - 'examples/*'
  - 'packages/*'

catalog:
  'typescript': ^5.8.3
  '@types/node': ^22.0.0
  'sass': ^1.86.3
  'vite': ^6.2.5
  'vitest': ^3.1.1
  'prettier': ^3.5.3
  '@vitest/browser': ^3.1.1
  'playwright': ^1.50.1

catalogs:
  react:
    'react': ^19.0.0
    'react-dom': ^19.0.0
    '@types/react': ^19.0.8
    '@types/react-dom': ^19.0.3
  formatter:
    '@ianvs/prettier-plugin-sort-imports': ^4.4.1
    prettier-plugin-packagejson: ^2.5.8
    prettier: ^3.4.2
  linter:
    '@eslint/js': ^9.22.0
    '@eslint/eslintrc': ^3.3.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.4
    eslint: ^9.22.0
    typescript-eslint: ^8.26.1
    eslint-config-next: ^15.2.3
    jiti: '^2.4.2'
