packages:
  - 'examples/*'
  - 'packages/*'

catalog:
  'typescript': ^5.8.3
  '@types/node': ^22.15.3
  'sass': ^1.87.0
  'sass-embedded': ^1.87.0
  'vite': ^6.3.4
  'vitest': ^3.1.2
  'prettier': ^3.5.3
  '@vitest/browser': ^3.1.2
  '@playwright/test': ^1.52.0

catalogs:
  react:
    'react': ^19.1.0
    'react-dom': ^19.1.0
    '@types/react': ^19.1.2
    '@types/react-dom': ^19.1.3
  formatter:
    '@ianvs/prettier-plugin-sort-imports': ^4.4.1
    prettier-plugin-packagejson: ^2.5.10
    prettier: ^3.5.3
  linter:
    '@eslint/js': ^9.26.0
    '@eslint/eslintrc': ^3.3.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.5
    eslint: ^9.26.0
    typescript-eslint: ^8.31.1
    jiti: '^2.4.2'
