packages:
  - 'examples/*'
  - 'packages/*'

catalog:
  'typescript': ^5.7.3
  '@types/node': ^22.0.0
  'sass': ^1.83.4
  'vite': ^6.0.5
  'vitest': ^3.0.5
  'prettier': ^3.4.2
  '@vitest/browser': ^3.0.5
  'playwright': ^1.50.1

catalogs:
  react:
    'react': ^19.0.0
    'react-dom': ^19.0.0
    '@types/react': ^19.0.8
    '@types/react-dom': ^19.0.3
  formatter:
    '@ianvs/prettier-plugin-sort-imports': ^4.4.1
    prettier-plugin-packagejson: ^2.5.8
    prettier: ^3.4.2
